### PR TITLE
Project is Done! Set up Distributables and Final Project

### PR DESCRIPTION
**Pull request by SamvritSrinath**
Project is Done! Merge into Main, Final Checks for everything.

### CODE REVIEW

**Review by mapersiani — APPROVED** [review]
Done! Good work team!

**Review by Angie-n — APPROVED** [review]
Looks great, go Akatsuki 7!

**Review by andronius-yang — APPROVED** [review]
Well done team! Looking through the pages, I think we should add links to our docs somewhere. Other than that, everything is good!

**Comment by n2singh** [comment]
Love to see it, so proud of us!!

**Comment by andronius-yang** [comment]
bro what

**Review by arnavkamdar — COMMENTED** [review]
Great work everyone! Super proud of this product, no issues from my end :)

**Pull request merged**
