### PR TITLE
Feat/matteo hashim/popup

### LINKED ISSUE #5: [US #1] Pop up Task
## Description

Create a pop up task web component that has all the attributes specified in the MIRO board.

 
## Frontend

On the webpage see if you can render the title and description(ignore styling for right now) 

Task Object needs to have a title, a priority that is selected from a drop down(with the ability to create a new label) a priority that ranges from P0 — P4, the expected time it takes. And the due date that opens up a calendar view for them to click on it(feel free to use an external library and style it). 

**Javascript Features**: Add a Filter button that allows you to filter by label(have this be a script that is assigned to a button) and also have a **sort by priority** button that reorders the tasks vertically based on priority. 

## Backend

Store this object in local storage and have routes to get it from the backend, we will migrate to files later. 

## Additional Information

Check out localstorage documentation and webcomponent documentation

https://developer.mozilla.org/en-US/docs/Web/API/Web_components
https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage

### PR DESCRIPTION
**Pull request by mapersiani**
Closes #5 

# Documentation For Popup

## Role of Popup

The role of this component is to have a popup feature when someone wants to add a task to their calendar.

## Intended Purpose

The popup is intended to open up when the user wants to create a new task. It will give them the option to input a title, description, and more. When the user is done, they can click "done" to add the task to their calendar. The user can also exit the popup by clicking anywhere outside of the box or on the "x" in the corner.

## Implementation/Syntax Approaches?

On our first try of implementing this component, we had a separate HTML, CSS, and JS file, but we did most things in our JS file. After we had a working product, we started to slowly move each language into their respective files. We first began by moving our CSS code in our JS file into a CSS file. This took us some time as we had to figure out how to link the CSS file into our JS file. We then moved our HTML component to its respective file which went pretty smoothly. We had to use fetch to get the contents of out HTML file into our JS file. Next, we moved a few lines of script that we had in our HTML file by simply cutting it and adding it to the bottom of the JS file. Lastly, after achieving the proper styling, we store all the values that the user inputs to local storage so they can be easily accessed.

The popup can be implemented with the following code: 
```html
<button id="open-popup">Add Task</button>
<script src="popup-component.js"></script>
```
## Requirements

The popup should allow the user to input details for a task. The background should blur to make the popup the center or attention. Furthermore, the popup should be intuitive and easy to use. Data should be stored locally to be easily accessed by the backend.

## Testing

For testing our popupcomponent, we used the LiveServer to periodically check any changes that were made and the effects of those changes. We also made a separate HTML called index.html purely for testing our code.

Image of popup
#### Authors

- Hashim Fituri
- Matteo Persiani

### CODE REVIEW

**Review by deenap23 — APPROVED** [review]
Functionality wise since we decided on leaving the task label as a text entry everything looks good to me! The styling is also consistent and aligns with what the micro/designer suggestions are. Looks good to me!

**Review by Angie-n — APPROVED** [review]
Could be difficult to enter information for smaller screens but otherwise looks good!

**Comment by SamvritSrinath** [comment]
Can the calendar showcase a Time(like a calendar then a time) —> as right now, only the calendar pops up to show the date for interactivity. 

Also it makes sense for label to be required, but can we default to have the Priority be nothing yet(and then check if it is either P1 —> P4), also the Expected Time can be empty and still submitted

**Review by arnavkamdar — CHANGES_REQUESTED** [review]
I think the component looks great, just a couple final details we might want to address: 
- We don't have any checks on the types of specific types of data right now, not sure if we need it. For instance, I can input the word "five" instead of '5' into the expected time section and it'll work. This is not expected behavior, since we want to eventually implement a feature that works with this expected time, so it needs to ensure that the right type of input is given to prevent larger bugs down the line. 
- One quick suggestion about the datetime-local input we're using for the calendar and time: if we set a `step` attribute to some number (say 900), we can change the interval between times if a user is scrolling through them. So if I was using arrow keys to select a time, it would increment like this as I press 'down': 0-15-30-45-0. This is opposed to what currently happens, which is 0-1-2... Small QOL improvement that wouldn't take too long to implement.

**Comment by SamvritSrinath** [comment]
LGTM!

**Pull request merged**
